# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget

class Ui_Settings(object):
    def setupUi(self, Settings):
        Settings.setObjectName("Settings")
        Settings.resize(798, 648)
        font = QtGui.QFont()
        font.setFamily("Sitka Subheading")
        font.setPointSize(16)
        Settings.setFont(font)
        self.gridLayout = QtWidgets.QGridLayout(Settings)
        self.gridLayout.setObjectName("gridLayout")
        self.main_frm = QtWidgets.QFrame(Settings)
        self.main_frm.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_frm.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_frm.setObjectName("main_frm")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.main_frm)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.header_frm = QtWidgets.QFrame(self.main_frm)
        self.header_frm.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.header_frm.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header_frm.setObjectName("header_frm")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.header_frm)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lblHead = QtWidgets.QLabel(self.header_frm)
        self.lblHead.setAlignment(QtCore.Qt.AlignCenter)
        self.lblHead.setObjectName("lblHead")
        self.gridLayout_3.addWidget(self.lblHead, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.header_frm, 0, 0, 1, 3)
        self.web_frm = QtWidgets.QFrame(self.main_frm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.web_frm.sizePolicy().hasHeightForWidth())
        self.web_frm.setSizePolicy(sizePolicy)
        self.web_frm.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.web_frm.setFrameShadow(QtWidgets.QFrame.Raised)
        self.web_frm.setObjectName("web_frm")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.web_frm)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.web_frm)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 4, 0, 1, 1)
        self.btnAdd_url = QtWidgets.QPushButton(self.web_frm)
        self.btnAdd_url.setObjectName("btnAdd_url")
        self.gridLayout_2.addWidget(self.btnAdd_url, 4, 3, 1, 1)
        self.lblWeb = QtWidgets.QLabel(self.web_frm)
        self.lblWeb.setObjectName("lblWeb")
        self.gridLayout_2.addWidget(self.lblWeb, 0, 0, 2, 3, QtCore.Qt.AlignHCenter)
        self.lstWeb = QtWidgets.QListView(self.web_frm)
        self.lstWeb.setObjectName("lstWeb")
        self.gridLayout_2.addWidget(self.lstWeb, 5, 0, 1, 3)
        self.textEdit_2 = QtWidgets.QTextEdit(self.web_frm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_2.sizePolicy().hasHeightForWidth())
        self.textEdit_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Sitka Subheading")
        font.setPointSize(13)
        self.textEdit_2.setFont(font)
        self.textEdit_2.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.textEdit_2.setOverwriteMode(False)
        self.textEdit_2.setAcceptRichText(True)
        self.textEdit_2.setObjectName("textEdit_2")
        self.gridLayout_2.addWidget(self.textEdit_2, 4, 1, 1, 1)
        self.btnRemove_web = QtWidgets.QPushButton(self.web_frm)
        self.btnRemove_web.setObjectName("btnRemove_web")
        self.gridLayout_2.addWidget(self.btnRemove_web, 5, 3, 1, 1, QtCore.Qt.AlignBottom)
        self.gridLayout_5.addWidget(self.web_frm, 1, 1, 1, 1)
        self.app_frm = QtWidgets.QFrame(self.main_frm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.app_frm.sizePolicy().hasHeightForWidth())
        self.app_frm.setSizePolicy(sizePolicy)
        self.app_frm.setMinimumSize(QtCore.QSize(363, 0))
        self.app_frm.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.app_frm.setFrameShadow(QtWidgets.QFrame.Raised)
        self.app_frm.setObjectName("app_frm")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.app_frm)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.btnFind = QtWidgets.QPushButton(self.app_frm)
        self.btnFind.setObjectName("btnFind")
        self.gridLayout_4.addWidget(self.btnFind, 3, 2, 1, 1, QtCore.Qt.AlignBottom)
        self.btnAdd_app = QtWidgets.QPushButton(self.app_frm)
        self.btnAdd_app.setObjectName("btnAdd_app")
        self.gridLayout_4.addWidget(self.btnAdd_app, 1, 2, 1, 1)
        self.lstApp = QtWidgets.QListView(self.app_frm)
        self.lstApp.setObjectName("lstApp")
        self.gridLayout_4.addWidget(self.lstApp, 2, 0, 2, 2)
        self.lblApp = QtWidgets.QLabel(self.app_frm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblApp.sizePolicy().hasHeightForWidth())
        self.lblApp.setSizePolicy(sizePolicy)
        self.lblApp.setObjectName("lblApp")
        self.gridLayout_4.addWidget(self.lblApp, 1, 0, 1, 1)
        self.btnRemove_app = QtWidgets.QPushButton(self.app_frm)
        self.btnRemove_app.setObjectName("btnRemove_app")
        self.gridLayout_4.addWidget(self.btnRemove_app, 2, 2, 1, 1, QtCore.Qt.AlignTop)
        self.lbl_app = QtWidgets.QLabel(self.app_frm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_app.sizePolicy().hasHeightForWidth())
        self.lbl_app.setSizePolicy(sizePolicy)
        self.lbl_app.setObjectName("lbl_app")
        self.gridLayout_4.addWidget(self.lbl_app, 0, 0, 1, 3, QtCore.Qt.AlignHCenter)
        self.comboBox = QtWidgets.QComboBox(self.app_frm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout_4.addWidget(self.comboBox, 1, 1, 1, 1)
        self.gridLayout_5.addWidget(self.app_frm, 1, 2, 1, 1)
        self.btnOptions = QtWidgets.QFrame(self.main_frm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnOptions.sizePolicy().hasHeightForWidth())
        self.btnOptions.setSizePolicy(sizePolicy)
        self.btnOptions.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.btnOptions.setFrameShadow(QtWidgets.QFrame.Raised)
        self.btnOptions.setObjectName("btnOptions")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.btnOptions)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.btnHelp = QtWidgets.QPushButton(self.btnOptions)
        self.btnHelp.setObjectName("btnHelp")
        self.gridLayout_6.addWidget(self.btnHelp, 0, 0, 1, 1, QtCore.Qt.AlignRight|QtCore.Qt.AlignBottom)
        self.gridLayout_5.addWidget(self.btnOptions, 2, 0, 1, 3)
        self.gridLayout.addWidget(self.main_frm, 0, 0, 1, 1)

        self.retranslateUi(Settings)
        QtCore.QMetaObject.connectSlotsByName(Settings)

    def retranslateUi(self, Settings):
        _translate = QtCore.QCoreApplication.translate
        Settings.setWindowTitle(_translate("Settings", "Form"))
        self.lblHead.setText(_translate("Settings", "Settings"))
        self.label.setText(_translate("Settings", "url:"))
        self.btnAdd_url.setText(_translate("Settings", "Add"))
        self.lblWeb.setText(_translate("Settings", "Website"))
        self.textEdit_2.setPlaceholderText(_translate("Settings", "http://google.com"))
        self.btnRemove_web.setText(_translate("Settings", "Remove"))
        self.btnFind.setText(_translate("Settings", "Find"))
        self.btnAdd_app.setText(_translate("Settings", "Add"))
        self.lblApp.setText(_translate("Settings", "App:"))
        self.btnRemove_app.setText(_translate("Settings", "Remove"))
        self.lbl_app.setText(_translate("Settings", "Programs"))
        self.btnHelp.setText(_translate("Settings", "Help"))

class App_Form(QWidget):
    def __init__(self, text):
        super().__init__()
        self.ui = Ui_Settings()
        self.ui.setupUi(self)

    def set_function_pack(self,function_pack):
        return None

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Settings = QtWidgets.QWidget()
    ui = Ui_Settings()
    ui.setupUi(Settings)
    Settings.show()
    sys.exit(app.exec_())